version: "3.9" 

networks:
  greenx-network:
    driver: bridge

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: dbpasswd
      MYSQL_DATABASE: all_tables
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
    networks:
      - greenx-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./data/backend/logs:/app/logs
    working_dir: /app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    env_file:
      - ./backend/.env
    environment:
      DB_URL: ${DB_URL}
      PYTHONPATH: /app
    depends_on:
      - db
    networks:
      - greenx-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    networks:
      - greenx-network
